"""fix order model

Revision ID: 8fd5d3836b27
Revises: 03ecbcd447a9
Create Date: 2025-12-12 20:42:27.499118
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8fd5d3836b27'
down_revision: Union[str, Sequence[str], None] = '03ecbcd447a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ITEMS TABLE UPDATES
    op.add_column('items', sa.Column('in_stock', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('availability_date', sa.Date(), nullable=True))
    op.add_column('items', sa.Column('created_at', sa.Date(), nullable=True))
    op.drop_column('items', 'is_available')

    # ORDERS TABLE UPDATES
    op.add_column('orders', sa.Column('delivery_boy_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))

    op.alter_column(
        'orders',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )

    # FIX: SAFE VARCHAR → INTEGER conversion
    op.alter_column(
        'orders',
        'quantity',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="quantity::integer"
    )

    op.create_foreign_key(
        None,
        'orders',
        'delivery_boys',
        ['delivery_boy_id'],
        ['id']
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'orders', type_='foreignkey')

    op.alter_column(
        'orders',
        'quantity',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True
    )

    op.alter_column(
        'orders',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'delivery_boy_id')

    op.add_column('items', sa.Column('is_available', sa.BOOLEAN(), nullable=True))
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'availability_date')
    op.drop_column('items', 'in_stock')

    # ### end Alembic commands ###
